spring.application.name=BankApps
spring.threads.virtual.enabled=true
# Server port
server.port=8083
# change to keycloak if run from docker
app.sso.url = http://localhost:8080
app.sso.issuer= http://localhost:8080/realms/master
logging.level.org.springframework.security=DEBUG

