spring.application.name=BankApps
spring.threads.virtual.enabled=true
# Server port
server.port=8081
# change to keycloak if run from docker
app.sso.url = ${KEYCLOAK_URL}
app.sso.issuer= ${KEYCLOAK_URL}/realms/master
logging.level.org.springframework.security=DEBUG

