spring.application.name=BankApps
spring.threads.virtual.enabled=true
# Server port
server.port=8081
#app.sso.issuer= http://localhost:8080/realms/master

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=test
spring.datasource.password=test

